name: УведомлениеПросроченных
title: Уведомление о просроченных задачах
titles:
  en: Overdue tasks notification
  de: Benachrichtigung über überfällige Aufgaben
  sr: Обавештење о прекораченим задацима
  az: Gecikmiş tapşırıq bildirişi
  es: Notificación de tareas vencidas
  fr: Notification des tâches en retard
  hy: Ծանուցում ժամկետանց առաջադրանքների մասին
  ka: შეტყობინება დაგვიანებული დავალებების შესახებ
  kk: Мерзімі өткен тапсырмалар туралы хабарлама
  pt: Notificação de tarefas atrasadas
  ro: Notificare sarcini restante
  tr: Gecikmiş görev bildirimi
  uk: Сповіщення про прострочені завдання
  uz: Kechikkan vazifalar haqida xabar berish
  zh: 逾期任务通知
params:
  - name: Кому
    type: string
    label: Кому
    labels:
      en: To
      de: An
      sr: Коме
      az: Kimə
      es: A quién
      fr: À qui
      hy: Ում
      ka: ვის
      kk: Кімге
      pt: Para quem
      ro: Către
      tr: Kime
      uk: Кому
      uz: Kimga
      zh: 收件人
