package langref

// functionDescriptors — глобальные функции. Наполняется в Task 3, далее
// поддерживается жёстким гейтом completeness_test.go. Сигнатуры и поведение
// сверены с реализациями в internal/dsl/interpreter/*.
var functionDescriptors = []Descriptor{

	// ─── Строки ─────────────────────────────────────────────────────────────
	{
		Name: "врег", Display: "ВРег", Aliases: []string{"Upper"}, Kind: KindFunc,
		Signature: "ВРег(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Переводит все символы строки в верхний регистр.",
		Example:   "ВРег(\"привет\") // \"ПРИВЕТ\"",
		Group:     "Строки",
	},
	{
		Name: "нрег", Display: "НРег", Aliases: []string{"Lower"}, Kind: KindFunc,
		Signature: "НРег(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Переводит все символы строки в нижний регистр.",
		Group:     "Строки",
	},
	{
		Name: "трег", Display: "ТРег", Aliases: []string{"TitleCase"}, Kind: KindFunc,
		Signature: "ТРег(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Делает каждое слово с заглавной буквы, остальные буквы строчными.",
		Group:     "Строки",
	},
	{
		Name: "сокрлп", Display: "СокрЛП", Aliases: []string{"TrimAll"}, Kind: KindFunc,
		Signature: "СокрЛП(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Убирает пробельные символы с обоих концов строки.",
		Group:     "Строки",
	},
	{
		Name: "сокрл", Display: "СокрЛ", Aliases: []string{"TrimLeft"}, Kind: KindFunc,
		Signature: "СокрЛ(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Убирает пробельные символы в начале строки (слева).",
		Group:     "Строки",
	},
	{
		Name: "сокрп", Display: "СокрП", Aliases: []string{"TrimRight"}, Kind: KindFunc,
		Signature: "СокрП(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Убирает пробельные символы в конце строки (справа).",
		Group:     "Строки",
	},
	{
		Name: "лев", Display: "Лев", Aliases: []string{"Left"}, Kind: KindFunc,
		Signature: "Лев(Строка, Длина)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Длина", Type: "число", Doc: "число первых символов"},
		},
		Returns: "строка",
		Doc:     "Возвращает указанное число первых (левых) символов строки.",
		Group:   "Строки",
	},
	{
		Name: "прав", Display: "Прав", Aliases: []string{"Right"}, Kind: KindFunc,
		Signature: "Прав(Строка, Длина)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Длина", Type: "число", Doc: "число последних символов"},
		},
		Returns: "строка",
		Doc:     "Возвращает указанное число последних (правых) символов строки.",
		Group:   "Строки",
	},
	{
		Name: "сред", Display: "Сред", Aliases: []string{"Mid"}, Kind: KindFunc,
		Signature: "Сред(Строка, Позиция[, Длина])",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Позиция", Type: "число", Doc: "начальная позиция, нумерация с 1"},
			{Name: "Длина", Type: "число", Doc: "число символов; без него — до конца строки", Optional: true},
		},
		Returns: "строка",
		Doc:     "Возвращает подстроку, начиная с позиции (нумерация с 1). Без длины — до конца строки.",
		Group:   "Строки",
	},
	{
		Name: "стрдлина", Display: "СтрДлина", Aliases: []string{"StrLen"}, Kind: KindFunc,
		Signature: "СтрДлина(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "число",
		Doc:       "Возвращает число символов в строке.",
		Group:     "Строки",
	},
	{
		Name: "стрнайти", Display: "СтрНайти", Aliases: []string{"StrFind"}, Kind: KindFunc,
		Signature: "СтрНайти(Строка, Подстрока)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Подстрока", Type: "строка"},
		},
		Returns: "число",
		Doc:     "Возвращает позицию первого вхождения подстроки (нумерация с 1) или 0, если не найдено.",
		Group:   "Строки",
	},
	{
		Name: "стрзаменить", Display: "СтрЗаменить", Aliases: []string{"StrReplace"}, Kind: KindFunc,
		Signature: "СтрЗаменить(Строка, Что, Чем)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Что", Type: "строка", Doc: "искомая подстрока"},
			{Name: "Чем", Type: "строка", Doc: "замена"},
		},
		Returns: "строка",
		Doc:     "Заменяет все вхождения подстроки «Что» на «Чем».",
		Group:   "Строки",
	},
	{
		Name: "стрразделить", Display: "СтрРазделить", Aliases: []string{"StrSplit"}, Kind: KindFunc,
		Signature: "СтрРазделить(Строка, Разделитель)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Разделитель", Type: "строка"},
		},
		Returns: "массив",
		Doc:     "Разбивает строку по разделителю и возвращает Массив подстрок.",
		Group:   "Строки",
	},
	{
		Name: "стрсоединить", Display: "СтрСоединить", Aliases: []string{"StrJoin"}, Kind: KindFunc,
		Signature: "СтрСоединить(Массив, Разделитель)",
		Params: []Param{
			{Name: "Массив", Type: "массив", Doc: "элементы для соединения"},
			{Name: "Разделитель", Type: "строка"},
		},
		Returns: "строка",
		Doc:     "Соединяет элементы Массива в строку через разделитель.",
		Group:   "Строки",
	},
	{
		Name: "стрсодержит", Display: "СтрСодержит", Aliases: []string{"StrContains"}, Kind: KindFunc,
		Signature: "СтрСодержит(Строка, Подстрока)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Подстрока", Type: "строка"},
		},
		Returns: "булево",
		Doc:     "Истина, если строка содержит подстроку.",
		Group:   "Строки",
	},
	{
		Name: "стрначинаетсяс", Display: "СтрНачинаетсяС", Aliases: []string{"StrStartsWith"}, Kind: KindFunc,
		Signature: "СтрНачинаетсяС(Строка, Префикс)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Префикс", Type: "строка"},
		},
		Returns: "булево",
		Doc:     "Истина, если строка начинается с указанного префикса.",
		Group:   "Строки",
	},
	{
		Name: "стрзаканчиваетсяна", Display: "СтрЗаканчиваетсяНа", Aliases: []string{"StrEndsWith"}, Kind: KindFunc,
		Signature: "СтрЗаканчиваетсяНа(Строка, Суффикс)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Суффикс", Type: "строка"},
		},
		Returns: "булево",
		Doc:     "Истина, если строка заканчивается указанным суффиксом.",
		Group:   "Строки",
	},
	{
		Name: "стрчисловхождений", Display: "СтрЧислоВхождений", Aliases: []string{"StrOccurrenceCount"}, Kind: KindFunc,
		Signature: "СтрЧислоВхождений(Строка, Подстрока)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Подстрока", Type: "строка"},
		},
		Returns: "число",
		Doc:     "Возвращает число непересекающихся вхождений подстроки в строку.",
		Group:   "Строки",
	},
	{
		Name: "стрчислострок", Display: "СтрЧислоСтрок", Aliases: []string{"StrLineCount"}, Kind: KindFunc,
		Signature: "СтрЧислоСтрок(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "число",
		Doc:       "Возвращает число строк в многострочном тексте (минимум 1).",
		Group:     "Строки",
	},
	{
		Name: "стрполучитьстроку", Display: "СтрПолучитьСтроку", Aliases: []string{"StrGetLine"}, Kind: KindFunc,
		Signature: "СтрПолучитьСтроку(Строка, НомерСтроки)",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "НомерСтроки", Type: "число", Doc: "нумерация с 1"},
		},
		Returns: "строка",
		Doc:     "Возвращает строку с указанным номером (нумерация с 1) из многострочного текста или пустую строку.",
		Group:   "Строки",
	},
	{
		Name: "стрсравнить", Display: "СтрСравнить", Aliases: []string{"StrCompare"}, Kind: KindFunc,
		Signature: "СтрСравнить(Строка1, Строка2)",
		Params: []Param{
			{Name: "Строка1", Type: "строка"},
			{Name: "Строка2", Type: "строка"},
		},
		Returns: "число",
		Doc:     "Сравнивает две строки без учёта регистра. Возвращает -1, 0 или 1.",
		Group:   "Строки",
	},
	{
		Name: "стршаблон", Display: "СтрШаблон", Aliases: []string{"StrTemplate"}, Kind: KindFunc,
		Signature: "СтрШаблон(Шаблон, Значение1[, Значение2, …])",
		Params: []Param{
			{Name: "Шаблон", Type: "строка", Doc: "с подстановками %1, %2, …"},
			{Name: "Значение1", Type: "произвольный", Doc: "подставляется вместо %1"},
		},
		Returns: "строка",
		Doc:     "Подставляет аргументы в шаблон по позициям %1, %2 и т.д.",
		Example: "СтрШаблон(\"Привет, %1!\", \"Иван\") // \"Привет, Иван!\"",
		Group:   "Строки",
	},
	{
		Name: "строка", Display: "Строка", Aliases: []string{"Str"}, Kind: KindFunc,
		Signature: "Строка(Значение)",
		Params:    []Param{{Name: "Значение", Type: "произвольный"}},
		Returns:   "строка",
		Doc:       "Преобразует значение в строку (число, дату, ссылку — по наименованию).",
		Group:     "Строки",
	},
	{
		Name: "символ", Display: "Символ", Aliases: []string{"Char", "Chr"}, Kind: KindFunc,
		Signature: "Символ(КодСимвола)",
		Params:    []Param{{Name: "КодСимвола", Type: "число", Doc: "код Unicode"}},
		Returns:   "строка",
		Doc:       "Возвращает символ по его коду Unicode.",
		Group:     "Строки",
	},
	{
		Name: "кодсимвола", Display: "КодСимвола", Aliases: []string{"CharCode"}, Kind: KindFunc,
		Signature: "КодСимвола(Строка[, Позиция])",
		Params: []Param{
			{Name: "Строка", Type: "строка"},
			{Name: "Позиция", Type: "число", Doc: "номер символа, нумерация с 1 (по умолчанию 1)", Optional: true},
		},
		Returns: "число",
		Doc:     "Возвращает код Unicode символа в указанной позиции (нумерация с 1) или 0 вне диапазона.",
		Group:   "Строки",
	},
	{
		Name: "нстр", Display: "НСтр", Aliases: []string{"NStr"}, Kind: KindFunc,
		Signature: "НСтр(ИсходнаяСтрока[, КодЯзыка])",
		Params: []Param{
			{Name: "ИсходнаяСтрока", Type: "строка", Doc: "формат \"ru = '…'; en = '…'\""},
			{Name: "КодЯзыка", Type: "строка", Doc: "по умолчанию \"ru\"", Optional: true},
		},
		Returns: "строка",
		Doc:     "Выбирает локализованную строку по коду языка. При отсутствии кода возвращает первый сегмент.",
		Group:   "Строки",
	},
	{
		Name: "пустаястрока", Display: "ПустаяСтрока", Aliases: []string{"IsBlankString"}, Kind: KindFunc,
		Signature: "ПустаяСтрока(Строка)",
		Params:    []Param{{Name: "Строка", Type: "строка"}},
		Returns:   "булево",
		Doc:       "Истина, если строка пуста или состоит только из пробельных символов.",
		Group:     "Строки",
	},
	{
		Name: "числопрописью", Display: "ЧислоПрописью", Aliases: []string{"AmountInWords"}, Kind: KindFunc,
		Signature: "ЧислоПрописью(Сумма[, Валюта])",
		Params: []Param{
			{Name: "Сумма", Type: "число"},
			{Name: "Валюта", Type: "строка", Doc: "код валюты, по умолчанию \"rub\"", Optional: true},
		},
		Returns: "строка",
		Doc:     "Возвращает текстовое представление денежной суммы прописью со склонением единиц и копейками.",
		Group:   "Строки",
	},
	{
		Name: "base64строка", Display: "Base64Строка", Aliases: []string{"Base64String"}, Kind: KindFunc,
		Signature: "Base64Строка(Текст)",
		Params:    []Param{{Name: "Текст", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Кодирует UTF-8 текст в строку Base64.",
		Group:     "Строки",
	},
	{
		Name: "base64значение", Display: "Base64Значение", Aliases: []string{"Base64Value"}, Kind: KindFunc,
		Signature: "Base64Значение(СтрокаBase64)",
		Params:    []Param{{Name: "СтрокаBase64", Type: "строка"}},
		Returns:   "строка",
		Doc:       "Декодирует строку Base64 в текст. При ошибке возвращает пустую строку.",
		Group:     "Строки",
	},

	// ─── Даты ───────────────────────────────────────────────────────────────
	{
		Name: "текущаядата", Display: "ТекущаяДата", Aliases: []string{"Today"}, Kind: KindFunc,
		Signature: "ТекущаяДата()",
		Returns:   "дата",
		Doc:       "Возвращает текущую дату с обнулённым временем (начало дня).",
		Group:     "Даты",
	},
	{
		Name: "текущаядатавремя", Display: "ТекущаяДатаВремя", Aliases: []string{"Now"}, Kind: KindFunc,
		Signature: "ТекущаяДатаВремя()",
		Returns:   "дата",
		Doc:       "Возвращает текущие дату и время.",
		Group:     "Даты",
	},
	{
		Name: "дата", Display: "Дата", Aliases: []string{"Date"}, Kind: KindFunc,
		Signature: "Дата(Год, Месяц, День[, Час, Минута, Секунда]) | Дата(Строка) | Дата(Число)",
		Params: []Param{
			{Name: "Год", Type: "число"},
			{Name: "Месяц", Type: "число"},
			{Name: "День", Type: "число"},
			{Name: "Час", Type: "число", Optional: true},
			{Name: "Минута", Type: "число", Optional: true},
			{Name: "Секунда", Type: "число", Optional: true},
		},
		Returns: "дата",
		Doc:     "Конструктор даты: из компонент, из строки (\"2026-05-11\", \"11.05.2026\") или числа (20260511). Невалидный ввод даёт пустую дату.",
		Group:   "Даты",
	},
	{
		Name: "год", Display: "Год", Aliases: []string{"Year"}, Kind: KindFunc,
		Signature: "Год(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает год даты.",
		Group:     "Даты",
	},
	{
		Name: "месяц", Display: "Месяц", Aliases: []string{"Month"}, Kind: KindFunc,
		Signature: "Месяц(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает номер месяца даты (1–12).",
		Group:     "Даты",
	},
	{
		Name: "день", Display: "День", Aliases: []string{"Day"}, Kind: KindFunc,
		Signature: "День(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает день месяца даты (1–31).",
		Group:     "Даты",
	},
	{
		Name: "час", Display: "Час", Aliases: []string{"Hour"}, Kind: KindFunc,
		Signature: "Час(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает час даты (0–23).",
		Group:     "Даты",
	},
	{
		Name: "минута", Display: "Минута", Aliases: []string{"Minute"}, Kind: KindFunc,
		Signature: "Минута(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает минуты даты (0–59).",
		Group:     "Даты",
	},
	{
		Name: "секунда", Display: "Секунда", Aliases: []string{"Second"}, Kind: KindFunc,
		Signature: "Секунда(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает секунды даты (0–59).",
		Group:     "Даты",
	},
	{
		Name: "деньнедели", Display: "ДеньНедели", Aliases: []string{"DayOfWeek"}, Kind: KindFunc,
		Signature: "ДеньНедели(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает день недели (Понедельник = 1, …, Воскресенье = 7).",
		Group:     "Даты",
	},
	{
		Name: "деньгода", Display: "ДеньГода", Aliases: []string{"DayOfYear"}, Kind: KindFunc,
		Signature: "ДеньГода(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает порядковый номер дня в году (1–366).",
		Group:     "Даты",
	},
	{
		Name: "неделягода", Display: "НеделяГода", Aliases: []string{"WeekOfYear"}, Kind: KindFunc,
		Signature: "НеделяГода(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "число",
		Doc:       "Возвращает номер недели в году (неделя 1 начинается 1 января, границы по понедельникам).",
		Group:     "Даты",
	},
	{
		Name: "добавитьдень", Display: "ДобавитьДень", Aliases: []string{"AddDay"}, Kind: KindFunc,
		Signature: "ДобавитьДень(Дата, Количество)",
		Params: []Param{
			{Name: "Дата", Type: "дата"},
			{Name: "Количество", Type: "число", Doc: "может быть отрицательным"},
		},
		Returns: "дата",
		Doc:     "Возвращает дату, сдвинутую на указанное число дней (может быть отрицательным).",
		Group:   "Даты",
	},
	{
		Name: "добавитьмесяц", Display: "ДобавитьМесяц", Aliases: []string{"AddMonth"}, Kind: KindFunc,
		Signature: "ДобавитьМесяц(Дата, Количество)",
		Params: []Param{
			{Name: "Дата", Type: "дата"},
			{Name: "Количество", Type: "число", Doc: "может быть отрицательным"},
		},
		Returns: "дата",
		Doc:     "Возвращает дату, сдвинутую на указанное число месяцев (может быть отрицательным).",
		Group:   "Даты",
	},
	{
		Name: "добавитьгод", Display: "ДобавитьГод", Aliases: []string{"AddYear"}, Kind: KindFunc,
		Signature: "ДобавитьГод(Дата, Количество)",
		Params: []Param{
			{Name: "Дата", Type: "дата"},
			{Name: "Количество", Type: "число", Doc: "может быть отрицательным"},
		},
		Returns: "дата",
		Doc:     "Возвращает дату, сдвинутую на указанное число лет (может быть отрицательным).",
		Group:   "Даты",
	},
	{
		Name: "разностьдат", Display: "РазностьДат", Aliases: []string{"DateDiff"}, Kind: KindFunc,
		Signature: "РазностьДат(Дата1, Дата2, Единица)",
		Params: []Param{
			{Name: "Дата1", Type: "дата", Doc: "начальная"},
			{Name: "Дата2", Type: "дата", Doc: "конечная"},
			{Name: "Единица", Type: "строка", Doc: "\"секунда\"/\"минута\"/\"час\"/\"день\"/\"месяц\"/\"год\""},
		},
		Returns: "число",
		Doc:     "Возвращает разность Дата2 − Дата1 в указанных единицах. По умолчанию (неизвестная единица) — в днях.",
		Group:   "Даты",
	},
	{
		Name: "началогода", Display: "НачалоГода", Aliases: []string{"BegYear"}, Kind: KindFunc,
		Signature: "НачалоГода(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает начало года для указанной даты (1 января, 00:00:00).",
		Group:     "Даты",
	},
	{
		Name: "конецгода", Display: "КонецГода", Aliases: []string{"EndYear"}, Kind: KindFunc,
		Signature: "КонецГода(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает конец года для указанной даты (31 декабря, 23:59:59).",
		Group:     "Даты",
	},
	{
		Name: "началомесяца", Display: "НачалоМесяца", Aliases: []string{"BegMonth"}, Kind: KindFunc,
		Signature: "НачалоМесяца(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает начало месяца для указанной даты (1-е число, 00:00:00).",
		Group:     "Даты",
	},
	{
		Name: "конецмесяца", Display: "КонецМесяца", Aliases: []string{"EndMonth"}, Kind: KindFunc,
		Signature: "КонецМесяца(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает конец месяца для указанной даты (последняя секунда последнего дня).",
		Group:     "Даты",
	},
	{
		Name: "началоквартала", Display: "НачалоКвартала", Aliases: []string{"BegQuarter"}, Kind: KindFunc,
		Signature: "НачалоКвартала(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает начало квартала для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "конецквартала", Display: "КонецКвартала", Aliases: []string{"EndQuarter"}, Kind: KindFunc,
		Signature: "КонецКвартала(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает конец квартала для указанной даты (последняя секунда).",
		Group:     "Даты",
	},
	{
		Name: "началонедели", Display: "НачалоНедели", Aliases: []string{"BegWeek"}, Kind: KindFunc,
		Signature: "НачалоНедели(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает начало недели (понедельник, 00:00:00) для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "конецнедели", Display: "КонецНедели", Aliases: []string{"EndWeek"}, Kind: KindFunc,
		Signature: "КонецНедели(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает конец недели (воскресенье, 23:59:59) для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "началодня", Display: "НачалоДня", Aliases: []string{"BegDay"}, Kind: KindFunc,
		Signature: "НачалоДня(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает начало дня (00:00:00) для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "конецдня", Display: "КонецДня", Aliases: []string{"EndDay"}, Kind: KindFunc,
		Signature: "КонецДня(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает конец дня (23:59:59) для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "началочаса", Display: "НачалоЧаса", Aliases: []string{"BegHour"}, Kind: KindFunc,
		Signature: "НачалоЧаса(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает начало часа (минуты и секунды обнулены) для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "конецчаса", Display: "КонецЧаса", Aliases: []string{"EndHour"}, Kind: KindFunc,
		Signature: "КонецЧаса(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает конец часа (59 минут 59 секунд) для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "началоминуты", Display: "НачалоМинуты", Aliases: []string{"BegMinute"}, Kind: KindFunc,
		Signature: "НачалоМинуты(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает начало минуты (секунды обнулены) для указанной даты.",
		Group:     "Даты",
	},
	{
		Name: "конецминуты", Display: "КонецМинуты", Aliases: []string{"EndMinute"}, Kind: KindFunc,
		Signature: "КонецМинуты(Дата)",
		Params:    []Param{{Name: "Дата", Type: "дата"}},
		Returns:   "дата",
		Doc:       "Возвращает конец минуты (59 секунд) для указанной даты.",
		Group:     "Даты",
	},

	// ─── Число ──────────────────────────────────────────────────────────────
	{
		Name: "число", Display: "Число", Aliases: []string{"Number"}, Kind: KindFunc,
		Signature: "Число(Значение)",
		Params:    []Param{{Name: "Значение", Type: "произвольный"}},
		Returns:   "число",
		Doc:       "Преобразует значение в число. Запятая трактуется как десятичный разделитель; при ошибке возвращает 0.",
		Group:     "Число",
	},
	{
		Name: "окр", Display: "Окр", Aliases: []string{"Round"}, Kind: KindFunc,
		Signature: "Окр(Число[, Точность, Режим])",
		Params: []Param{
			{Name: "Число", Type: "число"},
			{Name: "Точность", Type: "число", Doc: "число знаков после запятой (по умолчанию 0)", Optional: true},
			{Name: "Режим", Type: "число", Doc: "0 — математическое (по умолчанию), 1 — банковское", Optional: true},
		},
		Returns: "число",
		Doc:     "Округляет число до указанной точности. Режим 0 — округление от нуля (как Окр в 1С), 1 — банковское.",
		Group:   "Число",
	},
	{
		Name: "абс", Display: "Абс", Aliases: []string{"Abs"}, Kind: KindFunc,
		Signature: "Абс(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает абсолютное значение (модуль) числа.",
		Group:     "Число",
	},
	{
		Name: "цел", Display: "Цел", Aliases: []string{"Int"}, Kind: KindFunc,
		Signature: "Цел(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает целую часть числа (отбрасывает дробную, усечение к нулю).",
		Group:     "Число",
	},
	{
		Name: "макс", Display: "Макс", Aliases: []string{"Max"}, Kind: KindFunc,
		Signature: "Макс(Число1, Число2)",
		Params: []Param{
			{Name: "Число1", Type: "число"},
			{Name: "Число2", Type: "число"},
		},
		Returns: "число",
		Doc:     "Возвращает большее из двух чисел.",
		Group:   "Число",
	},
	{
		Name: "мин", Display: "Мин", Aliases: []string{"Min"}, Kind: KindFunc,
		Signature: "Мин(Число1, Число2)",
		Params: []Param{
			{Name: "Число1", Type: "число"},
			{Name: "Число2", Type: "число"},
		},
		Returns: "число",
		Doc:     "Возвращает меньшее из двух чисел.",
		Group:   "Число",
	},
	{
		Name: "exp", Display: "Exp", Kind: KindFunc,
		Signature: "Exp(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает экспоненту (e в степени аргумента).",
		Group:     "Число",
	},
	{
		Name: "log", Display: "Log", Kind: KindFunc,
		Signature: "Log(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает натуральный логарифм числа.",
		Group:     "Число",
	},
	{
		Name: "log10", Display: "Log10", Kind: KindFunc,
		Signature: "Log10(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает десятичный логарифм числа.",
		Group:     "Число",
	},
	{
		Name: "pow", Display: "Pow", Kind: KindFunc,
		Signature: "Pow(Основание, Степень)",
		Params: []Param{
			{Name: "Основание", Type: "число"},
			{Name: "Степень", Type: "число"},
		},
		Returns: "число",
		Doc:     "Возводит основание в указанную степень.",
		Group:   "Число",
	},
	{
		Name: "sqrt", Display: "Sqrt", Kind: KindFunc,
		Signature: "Sqrt(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает квадратный корень числа.",
		Group:     "Число",
	},
	{
		Name: "sin", Display: "Sin", Kind: KindFunc,
		Signature: "Sin(Угол)",
		Params:    []Param{{Name: "Угол", Type: "число", Doc: "в радианах"}},
		Returns:   "число",
		Doc:       "Возвращает синус угла (в радианах).",
		Group:     "Число",
	},
	{
		Name: "cos", Display: "Cos", Kind: KindFunc,
		Signature: "Cos(Угол)",
		Params:    []Param{{Name: "Угол", Type: "число", Doc: "в радианах"}},
		Returns:   "число",
		Doc:       "Возвращает косинус угла (в радианах).",
		Group:     "Число",
	},
	{
		Name: "tan", Display: "Tan", Kind: KindFunc,
		Signature: "Tan(Угол)",
		Params:    []Param{{Name: "Угол", Type: "число", Doc: "в радианах"}},
		Returns:   "число",
		Doc:       "Возвращает тангенс угла (в радианах).",
		Group:     "Число",
	},
	{
		Name: "asin", Display: "Asin", Kind: KindFunc,
		Signature: "Asin(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает арксинус (в радианах).",
		Group:     "Число",
	},
	{
		Name: "acos", Display: "Acos", Kind: KindFunc,
		Signature: "Acos(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает арккосинус (в радианах).",
		Group:     "Число",
	},
	{
		Name: "atan", Display: "Atan", Kind: KindFunc,
		Signature: "Atan(Число)",
		Params:    []Param{{Name: "Число", Type: "число"}},
		Returns:   "число",
		Doc:       "Возвращает арктангенс (в радианах).",
		Group:     "Число",
	},
	{
		Name: "распределить", Display: "Распределить", Aliases: []string{"Distribute"}, Kind: KindFunc,
		Signature: "Распределить(Сумма, Веса[, Точность])",
		Params: []Param{
			{Name: "Сумма", Type: "число", Doc: "распределяемая сумма"},
			{Name: "Веса", Type: "массив", Doc: "Массив чисел — пропорции"},
			{Name: "Точность", Type: "число", Doc: "знаков после запятой (по умолчанию 2)", Optional: true},
		},
		Returns: "массив",
		Doc:     "Пропорционально распределяет сумму по весам с гарантией сохранения итога. Возвращает Массив той же длины, что и Веса.",
		Group:   "Число",
	},

	// ─── Коллекции и JSON ───────────────────────────────────────────────────
	{
		Name: "прочитатьjson", Display: "ПрочитатьJSON", Aliases: []string{"ReadJSON"}, Kind: KindFunc,
		Signature: "ПрочитатьJSON(Текст)",
		Params:    []Param{{Name: "Текст", Type: "строка", Doc: "строка JSON"}},
		Returns:   "произвольный",
		Doc:       "Разбирает строку JSON в значение DSL (Соответствие, Массив, число, строку, булево).",
		Group:     "Коллекции и JSON",
	},
	{
		Name: "записатьjson", Display: "ЗаписатьJSON", Aliases: []string{"WriteJSON"}, Kind: KindFunc,
		Signature: "ЗаписатьJSON(Значение)",
		Params:    []Param{{Name: "Значение", Type: "произвольный", Doc: "Соответствие/Структура/Массив/примитив"}},
		Returns:   "строка",
		Doc:       "Сериализует значение DSL в строку JSON.",
		Group:     "Коллекции и JSON",
	},
	{
		Name: "выгрузитьвexcel", Display: "ВыгрузитьВExcel", Aliases: []string{"ExportExcel"}, Kind: KindFunc,
		Signature: "ВыгрузитьВExcel(Данные[, Заголовок])",
		Params: []Param{
			{Name: "Данные", Type: "массив", Doc: "Массив массивов; первый подмассив — заголовки колонок"},
			{Name: "Заголовок", Type: "строка", Optional: true},
		},
		Returns: "строка",
		Doc:     "Формирует файл XLSX из таблицы (первая строка — заголовки) и возвращает его содержимое в Base64.",
		Group:   "Коллекции и JSON",
	},
	{
		Name: "заполнитьзначениясвойств", Display: "ЗаполнитьЗначенияСвойств", Aliases: []string{"FillPropertyValues"}, Kind: KindFunc,
		Signature: "ЗаполнитьЗначенияСвойств(Приёмник, Источник[, СписокСвойств, ИсключаяСвойства])",
		Params: []Param{
			{Name: "Приёмник", Type: "объект", Doc: "объект/Структура, поддерживающий установку свойств"},
			{Name: "Источник", Type: "объект", Doc: "Структура, Соответствие или объект"},
			{Name: "СписокСвойств", Type: "строка", Doc: "имена через запятую — копировать только их", Optional: true},
			{Name: "ИсключаяСвойства", Type: "строка", Doc: "имена через запятую — пропустить", Optional: true},
		},
		Doc:   "Копирует одноимённые свойства из Источника в Приёмник. Пустой СписокСвойств означает «все свойства».",
		Group: "Коллекции и JSON",
	},

	// ─── Файлы ──────────────────────────────────────────────────────────────
	{
		Name: "декодироватьфайл", Display: "ДекодироватьФайл", Aliases: []string{"DecodeFile"}, Kind: KindFunc,
		Signature: "ДекодироватьФайл(Текст)",
		Params:    []Param{{Name: "Текст", Type: "строка", Doc: "содержимое файла"}},
		Returns:   "строка",
		Doc:       "Возвращает текст в UTF-8, при необходимости перекодируя из Windows-1251.",
		Group:     "Файлы",
	},
	{
		Name: "копироватьфайл", Display: "КопироватьФайл", Aliases: []string{"CopyFile"}, Kind: KindFunc,
		Signature: "КопироватьФайл(Откуда, Куда)",
		Params: []Param{
			{Name: "Откуда", Type: "строка", Doc: "путь к исходному файлу"},
			{Name: "Куда", Type: "строка", Doc: "путь назначения"},
		},
		Doc:   "Копирует содержимое файла из одного пути в другой.",
		Group: "Файлы",
	},
	{
		Name: "переместитьфайл", Display: "ПереместитьФайл", Aliases: []string{"MoveFile"}, Kind: KindFunc,
		Signature: "ПереместитьФайл(Откуда, Куда)",
		Params: []Param{
			{Name: "Откуда", Type: "строка"},
			{Name: "Куда", Type: "строка"},
		},
		Doc:   "Перемещает (переименовывает) файл из одного пути в другой.",
		Group: "Файлы",
	},
	{
		Name: "удалитьфайлы", Display: "УдалитьФайлы", Aliases: []string{"DeleteFiles"}, Kind: KindFunc,
		Signature: "УдалитьФайлы(Путь)",
		Params:    []Param{{Name: "Путь", Type: "строка", Doc: "файл или пустой каталог"}},
		Doc:       "Удаляет файл или пустой каталог. Нерекурсивно — дерево каталогов не сносит.",
		Group:     "Файлы",
	},
	{
		Name: "создатькаталог", Display: "СоздатьКаталог", Aliases: []string{"CreateDirectory"}, Kind: KindFunc,
		Signature: "СоздатьКаталог(Путь)",
		Params:    []Param{{Name: "Путь", Type: "строка"}},
		Doc:       "Создаёт каталог вместе со всеми отсутствующими родительскими каталогами.",
		Group:     "Файлы",
	},

	// ─── Картинки ───────────────────────────────────────────────────────────
	{
		Name: "сохранитькартинку", Display: "СохранитьКартинку", Aliases: []string{"PutImage"}, Kind: KindFunc,
		Signature: "СохранитьКартинку(ДанныеBase64, ТипMIME = \"\")",
		Params: []Param{
			{Name: "ДанныеBase64", Type: "строка", Doc: "картинка в Base64 (сырой или data-URL data:...;base64,...)"},
			{Name: "ТипMIME", Type: "строка", Doc: "тип картинки; по умолчанию image/png"},
		},
		Returns: "строка",
		Doc:     "Сохраняет картинку в хранилище и возвращает UUID бинарника — это значение кладётся в реквизит типа «Картинка». Пустой аргумент возвращает пустую строку.",
		Group:   "Картинки",
	},
	{
		Name: "найтифайлы", Display: "НайтиФайлы", Aliases: []string{"FindFiles"}, Kind: KindFunc,
		Signature: "НайтиФайлы(Путь, Маска)",
		Params: []Param{
			{Name: "Путь", Type: "строка", Doc: "каталог поиска"},
			{Name: "Маска", Type: "строка", Doc: "шаблон имени, например \"*.txt\""},
		},
		Returns: "массив",
		Doc:     "Возвращает Массив путей файлов в каталоге, подходящих под маску.",
		Group:   "Файлы",
	},

	// ─── HTTP ───────────────────────────────────────────────────────────────
	{
		Name: "httpполучить", Display: "HTTPПолучить", Aliases: []string{"HTTPGet"}, Kind: KindFunc,
		Signature: "HTTPПолучить(URL)",
		Params:    []Param{{Name: "URL", Type: "строка"}},
		Returns:   "HTTPОтвет",
		Doc:       "Выполняет GET-запрос по URL и возвращает объект HTTPОтвет (таймаут 30 с).",
		Group:     "HTTP",
	},
	{
		Name: "httpотправить", Display: "HTTPОтправить", Aliases: []string{"HTTPPost"}, Kind: KindFunc,
		Signature: "HTTPОтправить(URL, Тело)",
		Params: []Param{
			{Name: "URL", Type: "строка"},
			{Name: "Тело", Type: "строка", Doc: "тело запроса (Content-Type: application/json)"},
		},
		Returns: "HTTPОтвет",
		Doc:     "Выполняет POST-запрос по URL с указанным телом (application/json) и возвращает объект HTTPОтвет.",
		Group:   "HTTP",
	},

	// ─── HTTP-сервисы ───────────────────────────────────────────────────────
	{
		Name: "ответjson", Display: "ОтветJSON", Aliases: []string{"ResponseJSON"}, Kind: KindFunc,
		Signature: "ОтветJSON(КодСостояния, Значение)",
		Params: []Param{
			{Name: "КодСостояния", Type: "число", Doc: "HTTP-код ответа, например 200"},
			{Name: "Значение", Type: "произвольный", Optional: true, Doc: "Структура/Соответствие/Массив — сериализуется в JSON"},
		},
		Returns: "HTTPСервисОтвет",
		Doc:     "Строит ответ HTTP-сервиса с JSON-телом (Content-Type: application/json). Используется в обработчиках эндпоинтов /hs/*.",
		Group:   "HTTP-сервисы",
	},
	{
		Name: "ответтекст", Display: "ОтветТекст", Aliases: []string{"ResponseText"}, Kind: KindFunc,
		Signature: "ОтветТекст(КодСостояния, Текст, ТипСодержимого)",
		Params: []Param{
			{Name: "КодСостояния", Type: "число", Doc: "HTTP-код ответа, например 200"},
			{Name: "Текст", Type: "строка", Doc: "текстовое тело ответа"},
			{Name: "ТипСодержимого", Type: "строка", Optional: true, Doc: "заголовок Content-Type; без него тип определяется автоматически"},
		},
		Returns: "HTTPСервисОтвет",
		Doc:     "Строит ответ HTTP-сервиса с текстовым телом. Используется в обработчиках эндпоинтов /hs/*.",
		Group:   "HTTP-сервисы",
	},

	// ─── Email ──────────────────────────────────────────────────────────────
	{
		Name: "отправитьписьмо", Display: "ОтправитьПисьмо", Aliases: []string{"SendEmail"}, Kind: KindFunc,
		Signature: "ОтправитьПисьмо(Кому, Тема, Текст)",
		Params: []Param{
			{Name: "Кому", Type: "строка", Doc: "адрес получателя"},
			{Name: "Тема", Type: "строка"},
			{Name: "Текст", Type: "строка", Doc: "тело письма"},
		},
		Doc:   "Отправляет письмо по настроенному SMTP. Требует секцию email: в конфигурации; иначе вызов завершается ошибкой.",
		Group: "Email",
	},

	// ─── Транзакции ─────────────────────────────────────────────────────────
	{
		Name: "начатьтранзакцию", Display: "НачатьТранзакцию", Aliases: []string{"BeginTransaction"}, Kind: KindFunc,
		Signature: "НачатьТранзакцию()",
		Doc:       "Открывает транзакцию БД. Вложенный вызов создаёт точку сохранения (SAVEPOINT).",
		Group:     "Транзакции",
	},
	{
		Name: "зафиксироватьтранзакцию", Display: "ЗафиксироватьТранзакцию", Aliases: []string{"CommitTransaction"}, Kind: KindFunc,
		Signature: "ЗафиксироватьТранзакцию()",
		Doc:       "Фиксирует текущую транзакцию (или освобождает точку сохранения для вложенной).",
		Group:     "Транзакции",
	},
	{
		Name: "отменитьтранзакцию", Display: "ОтменитьТранзакцию", Aliases: []string{"RollbackTransaction"}, Kind: KindFunc,
		Signature: "ОтменитьТранзакцию()",
		Doc:       "Откатывает текущую транзакцию (или к точке сохранения для вложенной).",
		Group:     "Транзакции",
	},

	// ─── ИИ-помощник ────────────────────────────────────────────────────────
	{
		Name: "запросии", Display: "ЗапросИИ", Aliases: []string{"AIQuery"}, Kind: KindFunc,
		Signature: "ЗапросИИ(Промпт[, Параметры])",
		Params: []Param{
			{Name: "Промпт", Type: "строка", Doc: "текст запроса к модели"},
			{Name: "Параметры", Type: "структура", Doc: "Задача, Система, Формат, Температура", Optional: true},
		},
		Returns: "строка",
		Doc:     "Отправляет текстовый запрос ИИ-помощнику и возвращает ответ. Требует настроенного помощника.",
		Group:   "ИИ-помощник",
	},
	{
		Name: "запросииджейсон", Display: "ЗапросИИДжейсон", Aliases: []string{"AIQueryJSON"}, Kind: KindFunc,
		Signature: "ЗапросИИДжейсон(Промпт[, Параметры])",
		Params: []Param{
			{Name: "Промпт", Type: "строка"},
			{Name: "Параметры", Type: "структура", Doc: "Задача, Система, Температура", Optional: true},
		},
		Returns: "строка",
		Doc:     "Как ЗапросИИ, но запрашивает у модели строгий JSON и возвращает его строкой.",
		Group:   "ИИ-помощник",
	},
	{
		Name: "распознатьдокумент", Display: "РаспознатьДокумент", Aliases: []string{"RecognizeDocument"}, Kind: KindFunc,
		Signature: "РаспознатьДокумент(Путь, Промпт)",
		Params: []Param{
			{Name: "Путь", Type: "строка", Doc: "путь к файлу изображения/PDF"},
			{Name: "Промпт", Type: "строка", Doc: "что извлечь из документа"},
		},
		Returns: "строка",
		Doc:     "Распознаёт документ из файла через vision-запрос ИИ-помощника и возвращает ответ.",
		Group:   "ИИ-помощник",
	},
	{
		Name: "распознатьизображение", Display: "РаспознатьИзображение", Aliases: []string{"RecognizeImage"}, Kind: KindFunc,
		Signature: "РаспознатьИзображение(ДанныеBase64, ТипMIME, Промпт)",
		Params: []Param{
			{Name: "ДанныеBase64", Type: "строка", Doc: "изображение в Base64"},
			{Name: "ТипMIME", Type: "строка", Doc: "например image/png (по умолчанию image/png)"},
			{Name: "Промпт", Type: "строка"},
		},
		Returns: "строка",
		Doc:     "Распознаёт изображение из данных в памяти (без записи на диск) через vision-запрос ИИ-помощника.",
		Group:   "ИИ-помощник",
	},

	// ─── Сообщения и ошибки ─────────────────────────────────────────────────
	{
		Name: "сообщить", Display: "Сообщить", Aliases: []string{"Message"}, Kind: KindFunc,
		Signature: "Сообщить(Текст)",
		Params:    []Param{{Name: "Текст", Type: "произвольный"}},
		Doc:       "Выводит сообщение пользователю (в панель сообщений формы или лог фонового задания).",
		Group:     "Сообщения и ошибки",
	},
	{
		Name: "вызватьисключение", Display: "ВызватьИсключение", Kind: KindFunc,
		Signature: "ВызватьИсключение(Сообщение)",
		Params:    []Param{{Name: "Сообщение", Type: "строка", Doc: "текст ошибки"}},
		Doc:       "Прерывает выполнение и поднимает пользовательскую ошибку с указанным сообщением (перехватывается Попытка…Исключение).",
		Group:     "Сообщения и ошибки",
	},
	{
		Name: "error", Display: "Error", Kind: KindFunc,
		Signature: "Error(Сообщение)",
		Params:    []Param{{Name: "Сообщение", Type: "строка"}},
		Doc:       "Англоязычный синоним ВызватьИсключение: прерывает выполнение и поднимает ошибку (отменяет запись/проведение).",
		Group:     "Сообщения и ошибки",
	},
	{
		Name: "описаниеошибки", Display: "ОписаниеОшибки", Aliases: []string{"ErrorDescription"}, Kind: KindFunc,
		Signature: "ОписаниеОшибки()",
		Returns:   "строка",
		Doc:       "Возвращает текст перехваченной ошибки. Доступна только внутри блока Исключение.",
		Group:     "Сообщения и ошибки",
	},
	{
		Name: "информацияобошибке", Display: "ИнформацияОбОшибке", Aliases: []string{"ErrorInfo"}, Kind: KindFunc,
		Signature: "ИнформацияОбОшибке()",
		Returns:   "структура",
		Doc:       "Возвращает Структуру с полями Описание, НомерСтроки, Источник. Доступна только внутри блока Исключение.",
		Group:     "Сообщения и ошибки",
	},

	// ─── Значения и тип ─────────────────────────────────────────────────────
	{
		Name: "тип", Display: "Тип", Aliases: []string{"Type"}, Kind: KindFunc,
		Signature: "Тип(ИмяТипа)",
		Params:    []Param{{Name: "ИмяТипа", Type: "строка", Doc: "\"Число\", \"Строка\", \"Дата\"…"}},
		Returns:   "строка",
		Doc:       "Возвращает нормализованное имя типа-маркер для сравнения с результатом ТипЗнч().",
		Group:     "Значения и тип",
	},
	{
		Name: "типзнч", Display: "ТипЗнч", Aliases: []string{"TypeOf"}, Kind: KindFunc,
		Signature: "ТипЗнч(Значение)",
		Params:    []Param{{Name: "Значение", Type: "произвольный"}},
		Returns:   "строка",
		Doc:       "Возвращает имя типа значения (\"Число\", \"Строка\", \"Дата\", \"Массив\"…).",
		Group:     "Значения и тип",
	},
	{
		Name: "значениезаполнено", Display: "ЗначениеЗаполнено", Aliases: []string{"IsFilled"}, Kind: KindFunc,
		Signature: "ЗначениеЗаполнено(Значение)",
		Params:    []Param{{Name: "Значение", Type: "произвольный"}},
		Returns:   "булево",
		Doc:       "Истина, если значение не пустое (не nil, не \"\", не 0, не Ложь, не пустая коллекция/ссылка).",
		Group:     "Значения и тип",
	},
	{
		Name: "пустая", Display: "Пустая", Aliases: []string{"IsBlank"}, Kind: KindFunc,
		Signature: "Пустая(Значение)",
		Params:    []Param{{Name: "Значение", Type: "произвольный"}},
		Returns:   "булево",
		Doc:       "Истина, если значение пустое: nil, пустая строка, 0, Ложь, пустая коллекция или пустая ссылка.",
		Group:     "Значения и тип",
	},
	{
		Name: "пустаяссылка", Display: "ПустаяСсылка", Aliases: []string{"IsEmptyRef"}, Kind: KindFunc,
		Signature: "ПустаяСсылка(Значение)",
		Params:    []Param{{Name: "Значение", Type: "произвольный", Doc: "nil, строка (UUID или \"\") или ссылка"}},
		Returns:   "булево",
		Doc:       "Узкий предикат именно для ссылок: истина для пустой ссылки. В отличие от Пустая, 0/Ложь/пустая коллекция пустой ссылкой не считаются.",
		Group:     "Значения и тип",
	},
	{
		Name: "формат", Display: "Формат", Aliases: []string{"Format"}, Kind: KindFunc,
		Signature: "Формат(Значение, СтрокаФормата)",
		Params: []Param{
			{Name: "Значение", Type: "произвольный", Doc: "число или дата"},
			{Name: "СтрокаФормата", Type: "строка", Doc: "например \"ЧДЦ=2; ЧРГ=' '\" или \"ДФ=dd.MM.yyyy\""},
		},
		Returns: "строка",
		Doc:     "Форматирует число (ЧДЦ — знаков после запятой, ЧРГ — разделитель групп) или дату (ДФ — шаблон) в строку.",
		Group:   "Значения и тип",
	},
	{
		Name: "вычислить", Display: "Вычислить", Aliases: []string{"Eval"}, Kind: KindFunc,
		Signature: "Вычислить(Выражение)",
		Params:    []Param{{Name: "Выражение", Type: "строка", Doc: "DSL-выражение"}},
		Returns:   "произвольный",
		Doc:       "Разбирает строку как выражение DSL и вычисляет его в текущем контексте переменных.",
		Group:     "Значения и тип",
	},

	// ─── Глобальный контекст ────────────────────────────────────────────────
	{
		Name: "справочники", Display: "Справочники", Aliases: []string{"Catalogs"}, Kind: KindFunc,
		Signature: "Справочники.ИмяСправочника",
		Doc:       "Глобальный объект доступа к справочникам: Справочники.X.НайтиПоКоду(...), .Создать() и т.п.",
		Group:     "Глобальный контекст",
	},
	{
		Name: "документы", Display: "Документы", Aliases: []string{"Documents"}, Kind: KindFunc,
		Signature: "Документы.ИмяДокумента",
		Doc:       "Глобальный объект доступа к документам: Документы.X.Создать(), .Записать(), .Провести(), .НайтиПоНомеру(...).",
		Group:     "Глобальный контекст",
	},
	{
		Name: "регистрынакопления", Display: "РегистрыНакопления", Aliases: []string{"AccumulationRegisters"}, Kind: KindFunc,
		Signature: "РегистрыНакопления.ИмяРегистра",
		Doc:       "Глобальный объект доступа к регистрам накопления: .Остатки(), .Обороты(), .ВыбратьПоРегистратору(Док).",
		Group:     "Глобальный контекст",
	},
	{
		Name: "предопределённыезначения", Display: "ПредопределённыеЗначения", Aliases: []string{"PredefinedValues"}, Kind: KindFunc,
		Signature: "ПредопределённыеЗначения.Справочник.Элемент",
		Doc:       "Доступ к предопределённым элементам справочников по имени: ПредопределённыеЗначения.X.Элемент.",
		Group:     "Глобальный контекст",
	},
	{
		Name: "текущийпользователь", Display: "ТекущийПользователь", Aliases: []string{"CurrentUser"}, Kind: KindFunc,
		Signature: "ТекущийПользователь()",
		Returns:   "структура",
		Doc:       "Возвращает объект текущего пользователя с полями ИД, Имя, ПолноеИмя, Админ.",
		Group:     "Глобальный контекст",
	},
	{
		Name: "имяпользователя", Display: "ИмяПользователя", Aliases: []string{"UserName"}, Kind: KindFunc,
		Signature: "ИмяПользователя()",
		Returns:   "строка",
		Doc:       "Возвращает логин текущего пользователя (пустую строку для фоновых заданий).",
		Group:     "Глобальный контекст",
	},
	{
		Name: "значениереквизитаобъекта", Display: "ЗначениеРеквизитаОбъекта", Aliases: []string{"ObjectAttributeValue"}, Kind: KindFunc,
		Signature: "ЗначениеРеквизитаОбъекта(Ссылка, ИмяРеквизита)",
		Params: []Param{
			{Name: "Ссылка", Type: "ссылка"},
			{Name: "ИмяРеквизита", Type: "строка"},
		},
		Returns: "произвольный",
		Doc:     "Читает значение реквизита объекта по ссылке отдельным запросом к БД. Ссылочный реквизит возвращается ссылкой; пустая ссылка — nil; неверное имя — ошибка.",
		Group:   "Глобальный контекст",
	},
	{
		Name: "ссылканаобъект", Display: "СсылкаНаОбъект", Aliases: []string{"ObjectRef"}, Kind: KindFunc,
		Signature: "СсылкаНаОбъект(Объект)",
		Params: []Param{
			{Name: "Объект", Type: "ссылка"},
		},
		Returns: "строка",
		Doc:     "Возвращает URL карточки объекта (/ui/<вид>/<сущность>/<id>) по ссылке — для ссылок на странице (план 66). Пустая/нессылочная величина — пустая строка.",
		Group:   "Глобальный контекст",
	},
	{
		Name: "блокировкаданных", Display: "БлокировкаДанных", Aliases: []string{"DataLock"}, Kind: KindFunc,
		Signature: "БлокировкаДанных()",
		Returns:   "объект",
		Doc:       "Возвращает новый объект управляемой блокировки данных, привязанный к менеджеру блокировок сервера.",
		Group:     "Глобальный контекст",
	},
}
